# Generated by Django 3.2 on 2021-04-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210417_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_time',
        ),
    ]
