# Generated by Django 3.2 on 2021-04-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210417_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(verbose_name='分类名称'),
        ),
    ]
