# Generated by Django 3.2 on 2021-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_group_permission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='group',
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ManyToManyField(db_constraint=False, to='blog.Group'),
        ),
    ]
